Repository rust-headless-chrome/rust-headless-chrome, pull requests merged in 2023-02, with the labels that each got.

#365 call get_document() in find_elements_by_xpath
  src/browser/tab/mod.rs
Labels: bug

#369 Handle more `.unwrap()`'s
  src/browser/fetcher.rs
  src/browser/mod.rs
  src/browser/process.rs
  src/browser/tab/mod.rs
  src/testing_utils/logging.rs
  src/testing_utils/server.rs
  src/types.rs
Labels: cleanup

#370 Updated to `base64` v0.21
  Cargo.toml
  src/browser/tab/mod.rs
Labels: dependencies

#375 Add derive(Debug) and tracing logging
  src/browser/fetcher.rs
  src/browser/process.rs
Labels: enhancement

#372 Updated Chrome revision and added Mac_Arm chrome installation
  src/browser/fetcher.rs
Labels: enhancement

#377 Cache Attributes, Tag Name and Value on Element creation
  src/browser/tab/element/mod.rs
Labels: enhancement

#380 Added installation latest version of chrome and refactored fetcher
  src/browser/fetcher.rs
  src/browser/mod.rs
  src/lib.rs
Labels: enhancement
