Repository rust-headless-chrome/rust-headless-chrome, pull requests merged in 2024-01, with the labels that each got.

#451 docs: remove outdated fetch setting info
  README.md
Labels: cleanup

#452 chore: enable ureq proxy-from-env
  Cargo.toml
Labels: enhancement

#447 Call Browser.Close on drop
  src/browser/mod.rs
Labels: enhancement

#454 fix: find_element_by_xpath doesn't return Error: No element found
  src/browser/tab/mod.rs
Labels: bugfix
